"""NAAC TAH (大興) - the third facility profile, and its duty-code grammar.

Source: `NAAC更期代號註解.xlsx`, `NAAC編更安排1.docx` and `NAAC覆診地點代號.csv`,
delivered by Cherry Siu on ClickUp tasks 2.2 and 4.1 on 31 Jul 2026. The extracted
dictionaries live beside this module in `data/`; `docs/naac/README.md` records
what was extracted, what was deliberately left out of the repository, and why.

Why this home needs its own module rather than another entry in `vocab.py`
--------------------------------------------------------------------------
Homes A and B each print a legend of eight or nine duty codes, so their windows
fit in a tuple. NAAC prints **279**, and they are not an arbitrary list - they
are generated by a grammar the home applies consistently:

    A7      letter A = 8 hours, digits 7 = starts 07:00  -> 07:00-15:00
    A7s     + s = 30 minutes                             -> 07:00-15:30
    A7x     + x = 10 minutes                             -> 07:00-15:10
    A7#     + # = duty supervisor on that shift          -> 07:00-15:00
    A7N10   A7 then N from 22:00                         -> two windows, 17h

Enumerating 279 rows by hand would be a transcription exercise with 279 chances
to be wrong. So the dictionary is loaded from the home's own sheet, and the
grammar is implemented once here as a cross-check: `derive_window` reads the
code, `load_shift_codes` reads the sheet, and `test_mvp_naac.py` asserts they
agree. Where they disagree the sheet wins - it is what the home actually pays
against - and the disagreement is reported rather than silently resolved.

Hours are taken from the sheet's own `時數` column rather than computed from the
clock times, because they are not always the same number: a shift with an unpaid
meal break is on the floor longer than it is paid for, and payroll follows the
column.
"""
from __future__ import annotations

import csv
import functools
import pathlib
import re
from dataclasses import dataclass

from .vocab import FacilityProfile, SheetProfile, ShiftWindow

DATA = pathlib.Path(__file__).resolve().parent / "data"

SHIFT_CODES_CSV = DATA / "naac_shift_codes.csv"
ESCORT_LOCATIONS_CSV = DATA / "naac_escort_locations.csv"
TASK_CODES_CSV = DATA / "naac_task_codes.csv"


# ── the code grammar ─────────────────────────────────────────────────────────
# Letter -> paid duration in minutes, from 更期代號註解. P is the exception: it is
# defined by when it ends (22:00), not by how long it runs, so it has no entry
# here and `derive_window` computes its length from the start time.
LETTER_MINUTES: dict[str, int] = {
    "A": 8 * 60,
    "B": 9 * 60,
    "C": 3 * 60,       # sleepover: 22:00-22:30 plus 06:30-07:00 the next morning
    "F": 6 * 60,
    "G": 7 * 60,
    "K": 10 * 60,
    "N": 9 * 60,       # overnight
    "S": 4 * 60,
}

# Suffix modifiers, in minutes. Applied after the letter's base duration.
MODIFIER_MINUTES: dict[str, int] = {"s": 30, "x": 10, "v": 5}

# The hour P shifts finish at, whatever time they start.
P_SHIFT_END = 22 * 60

# Sleepover C is two short windows around a night spent on the premises.
C_SEGMENTS = ({"start": "22:00", "end": "22:30"}, {"start": "06:30", "end": "07:00"})

_CODE = re.compile(
    r"^(?P<letter>[ABCFGKNPS])"
    r"(?P<digits>\d{1,4})?"
    r"(?P<modifier>[sxv])?"
    r"(?P<duty>#)?$"
)


def _start_minutes(letter: str, digits: str) -> int | None:
    """Digits after the letter are a start time, written the way a person says it.

    The home writes 1 to 4 digits and expects the reader to know the shift: `A7`
    is seven in the morning, `A1030` is half past ten, `P1` is one in the
    afternoon. Four digits are already 24-hour (`A0610`), three are h:mm, and one
    or two are an hour that has to be read against the shift letter - a P shift
    starting at "1" starts at 13:00, an A shift starting at "7" starts at 07:00.
    """
    if not digits:
        return None
    if len(digits) == 4:
        hour, minute = int(digits[:2]), int(digits[2:])
    elif len(digits) == 3:
        hour, minute = int(digits[0]), int(digits[1:])
    else:
        hour, minute = int(digits), 0
    if minute > 59:
        return None
    # Afternoon and night codes count from noon; 12 is already correct.
    #
    # K is not one of them, despite K10 being the long-night duty. K7, K8, K9,
    # K730 and K1230 are all ten-hour *day* shifts starting at the hour they
    # name, so the letter cannot be what makes K10 an overnight - only the sheet
    # can, and it does. K10 and K10s are therefore left as known grammar/sheet
    # disagreements rather than special-cased into the grammar.
    if letter in {"P", "N"} and hour < 12:
        hour += 12
    elif letter not in {"P", "N"} and hour < 6:
        # An A shift written "1" is 13:00 - no home starts a morning duty at 01:00.
        hour += 12
    if hour > 23:
        return None
    return hour * 60 + minute


def _hhmm(minutes: int) -> str:
    return f"{(minutes // 60) % 24:02d}:{minutes % 60:02d}"


@dataclass(frozen=True)
class DerivedWindow:
    """What the grammar alone says a code means."""

    code: str
    start: str | None
    end: str | None
    paid_minutes: int | None
    duty_supervisor: bool
    segments: tuple[dict[str, str], ...] = ()


def derive_window(code: str) -> DerivedWindow | None:
    """Read a duty code by its grammar. None when the code is not in the grammar
    (leave codes, ad-hoc `1-6p` hour ranges, the `/` not-in-post marker)."""
    code = (code or "").strip()
    if not code:
        return None

    combined = _split_combined(code)
    if combined:
        return combined

    match = _CODE.match(code)
    if not match:
        return None
    letter = match.group("letter")
    digits = match.group("digits") or ""
    modifier = match.group("modifier")
    duty = bool(match.group("duty"))

    start = _start_minutes(letter, digits)
    if letter == "C":
        return DerivedWindow(code, "22:00", "07:00", LETTER_MINUTES["C"], duty,
                             C_SEGMENTS)
    if start is None:
        return None

    if letter == "P":
        # Defined by its end, not its length.
        length = P_SHIFT_END - start
        if length <= 0:
            return None
    else:
        length = LETTER_MINUTES[letter]
    length += MODIFIER_MINUTES.get(modifier, 0)
    return DerivedWindow(code, _hhmm(start), _hhmm(start + length), length, duty)


def _split_combined(code: str) -> DerivedWindow | None:
    """`A7N10`, `G7sN10`, `P1C` - two duties written as one cell.

    Two disjoint windows in one day, the same shape as Home A's A/N split shift,
    so it is stored the same way and `paid_minutes` sums the segments instead of
    measuring the gap between them.

    `…C` is the sleepover variant: a day duty, then 22:00-22:30 and 06:30-07:00
    on the premises. Three windows, and the three paid hours the home counts for
    C are a standing allowance rather than the one hour those windows measure -
    so the sheet's 時數 is what payroll uses, as everywhere else here.
    """
    match = re.match(r"^([ABGFPK]\d{1,4}[sxv]?)(N\d{2,4}|C)(#)?$", code)
    if not match:
        return None
    day = derive_window(match.group(1))
    if not day or day.paid_minutes is None or not (day.start and day.end):
        return None
    duty = bool(match.group(3))

    if match.group(2) == "C":
        return DerivedWindow(
            code=code,
            start=day.start,
            end=C_SEGMENTS[-1]["end"],
            paid_minutes=day.paid_minutes + LETTER_MINUTES["C"],
            duty_supervisor=duty,
            segments=({"start": day.start, "end": day.end}, *C_SEGMENTS),
        )

    night = derive_window(match.group(2))
    if not night or night.paid_minutes is None:
        return None
    return DerivedWindow(
        code=code,
        start=day.start,
        end=night.end,
        paid_minutes=day.paid_minutes + night.paid_minutes,
        duty_supervisor=duty,
        segments=({"start": day.start, "end": day.end},
                  {"start": night.start, "end": night.end}),
    )


# ── the home's own sheet ─────────────────────────────────────────────────────
_TIME = re.compile(r"^(\d{1,2})(?::(\d{2}))?(?:(\d{2}))?\s*([ap])?$", re.IGNORECASE)


def parse_clock(token: str, *, default_meridiem: str | None = None) -> int | None:
    """'7a' -> 420, '3p' -> 900, '1030a' -> 630, '0610' -> 370, '9' -> None.

    The sheet's Remarks column writes times the way the roster does, so `a`/`p`
    is the meridiem and a bare number inherits the one from the other side of the
    range - "1-9p" is 13:00 to 21:00, not 01:00 to 21:00.
    """
    token = (token or "").strip().lower().replace(" ", "")
    if not token:
        return None
    if re.fullmatch(r"\d{4}", token):          # 24-hour, as in "0610-1420"
        hour, minute = int(token[:2]), int(token[2:])
        return hour * 60 + minute if hour < 24 and minute < 60 else None
    match = _TIME.match(token)
    if not match:
        return None
    hour = int(match.group(1))
    minute = int(match.group(2) or match.group(3) or 0)
    meridiem = (match.group(4) or default_meridiem or "").lower()
    if minute > 59 or hour > 23:
        return None
    if meridiem == "p" and hour < 12:
        hour += 12
    elif meridiem == "a" and hour == 12:
        hour = 0
    return hour * 60 + minute


def parse_time_range(text: str) -> tuple[tuple[str, str], ...]:
    """The Remarks column -> duty windows.

    Handles the four forms the sheet uses: `7a-3p`, `0610-1420`, and the split
    shift written either `7a-3p+10p-7a(翌日)` or `7a至3p至翌日7a`. Prose entries
    (leave descriptions, `未到職`) return empty.
    """
    text = (text or "").strip()
    if not text or not re.search(r"\d", text):
        return ()
    # 至 is "to" and 翌日 is "next day"; both are punctuation for our purposes.
    normalised = text.replace("至", "-").replace("翌日", "").replace("－", "-")
    windows: list[tuple[str, str]] = []
    for part in normalised.split("+"):
        part = re.sub(r"[（(].*?[)）]", "", part)
        # Some rows carry an unbalanced bracket once 翌日 is removed
        # ("1015p-715a翌日)"), so strip any survivors rather than let the row fail.
        part = part.strip(" ()（）")
        if "-" not in part:
            continue
        left, _, right = part.partition("-")
        # Resolve a bare left-hand number against the right-hand meridiem.
        right_meridiem = "p" if right.strip().lower().endswith("p") else (
            "a" if right.strip().lower().endswith("a") else None)
        start = parse_clock(left, default_meridiem=right_meridiem)
        end = parse_clock(right)
        if start is None or end is None:
            continue
        windows.append((_hhmm(start), _hhmm(end)))
    return tuple(windows)


@dataclass(frozen=True)
class NaacShiftCode:
    """One row of the home's 代號及時數 sheet."""

    code: str
    hours: float
    windows: tuple[tuple[str, str], ...]
    category_zh: str
    time_range: str
    duty_supervisor: bool
    is_working: bool
    am_fraction: float
    pm_fraction: float
    night_fraction: float
    sleepover_fraction: float
    ph_fraction: float

    @property
    def paid_minutes(self) -> int:
        return round(self.hours * 60)


def _f(value: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


@functools.lru_cache(maxsize=1)
def load_shift_codes() -> dict[str, NaacShiftCode]:
    """The home's duty dictionary, keyed by code."""
    out: dict[str, NaacShiftCode] = {}
    with SHIFT_CODES_CSV.open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            code = (row["code"] or "").strip()
            # '/' is the home's marker for "not in post this cycle" - a spacer in
            # the grid so the hours columns still add up, not a duty.
            if not code or code == "/":
                continue
            hours = _f(row["hours"])
            out[code] = NaacShiftCode(
                code=code,
                hours=hours,
                windows=parse_time_range(row["time_range"]),
                category_zh=(row["category_zh"] or "").strip(),
                time_range=(row["time_range"] or "").strip(),
                duty_supervisor=bool(_f(row["duty_supervisor"])),
                is_working=hours > 0,
                am_fraction=_f(row["am_fraction"]),
                pm_fraction=_f(row["pm_fraction"]),
                night_fraction=_f(row["night_fraction"]),
                sleepover_fraction=_f(row["sleepover_fraction"]),
                ph_fraction=_f(row["ph_fraction"]),
            )
    return out


@functools.lru_cache(maxsize=1)
def load_escort_locations() -> dict[str, dict[str, str]]:
    """Medical-escort location codes, keyed by code.

    Two places share `TMH` and two share `CPH` in the home's own sheet, so the
    first wins here and every place stays listed under `places`. The code is what
    goes in the roster cell; disambiguating the two TMH departments is the
    appointment's business, not the roster's.
    """
    out: dict[str, dict[str, str]] = {}
    with ESCORT_LOCATIONS_CSV.open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            code = (row["code"] or "").strip()
            if not code:
                continue
            entry = out.setdefault(code, {
                "code": code, "name_en": (row["name_en"] or "").strip(),
                "places": [],
            })
            entry["places"].append((row["place_zh"] or "").strip())
    return out


@dataclass(frozen=True)
class NaacTaskCode:
    code: str
    category: str
    name_en: str
    name_zh: str
    window: str
    needs_location: bool
    notes: str


@functools.lru_cache(maxsize=1)
def load_task_codes() -> dict[str, NaacTaskCode]:
    """Task markers written into a roster cell next to the duty code."""
    out: dict[str, NaacTaskCode] = {}
    with TASK_CODES_CSV.open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            code = (row["code"] or "").strip()
            if not code:
                continue
            out[code] = NaacTaskCode(
                code=code,
                category=(row["category"] or "").strip(),
                name_en=(row["name_en"] or "").strip(),
                name_zh=(row["name_zh"] or "").strip(),
                window=(row["window"] or "").strip(),
                needs_location=(row["needs_location"] or "").strip().lower() == "true",
                notes=(row["notes"] or "").strip(),
            )
    return out


def escort_codes() -> frozenset[str]:
    return frozenset(load_escort_locations())


def location_required_task_codes() -> frozenset[str]:
    return frozenset(c for c, t in load_task_codes().items() if t.needs_location)


# ── the profile ──────────────────────────────────────────────────────────────
def _window(spec: NaacShiftCode) -> ShiftWindow:
    segments = tuple({"start": s, "end": e} for s, e in spec.windows)
    label = spec.category_zh or spec.code
    if len(segments) > 1:
        return ShiftWindow(code=spec.code, label=label,
                           start=segments[0]["start"], end=segments[-1]["end"],
                           segments=segments, is_working=spec.is_working)
    if segments:
        return ShiftWindow(code=spec.code, label=label,
                           start=segments[0]["start"], end=segments[0]["end"],
                           is_working=spec.is_working)
    return ShiftWindow(code=spec.code, label=label, is_working=spec.is_working)


@functools.lru_cache(maxsize=1)
def shift_windows() -> tuple[ShiftWindow, ...]:
    return tuple(_window(spec) for spec in load_shift_codes().values())


@functools.lru_cache(maxsize=1)
def profile() -> FacilityProfile:
    """NAAC as a `FacilityProfile`, so the existing importer and seeder reach it
    through exactly the same interface as Homes A and B."""
    return FacilityProfile(
        code="NAAC",
        name="NAAC TAH 大興 (屯門)",
        cycle_type="42day",
        scheduling_cycle_days=42,       # the home rosters a 6-week cycle
        sheets=(SheetProfile("tahduty", shift_windows(),
                             "TAHDuty - HP / HW / SW / 家舍導師 / WA / PCW / Cook / WM"),),
        task_prefixes=("A", "P", "N", "B", "G", "K"),
        notes=(
            "279 duty codes, generated by a grammar: letter = paid duration, "
            "digits = start time, s/x/v = +30/+10/+5 minutes, # = duty supervisor.",
            "Dual working week: 44h office and therapists, 49h frontline "
            "(WA/PCW/Cook/WM) at 8h10m a day, from 2021-01-04.",
            "Escort location codes are per assignment, not per task definition.",
        ),
    )
